# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1f78e2c0ba1253f295188db99b497fcf2edf89d69488a9365d164cfcb3014d3673beeb7a8fdbf362219bca25b604327cb195efe9087fc5c61ac20b8e4c6a49c

test:
  secret_key_base: ae82e89c487f54ca6e4b47a3098b8b2114ae14ba8acab0a281d76c75ddeae7de43ff12ad9c492767dd267bacf64aecab6c027b28a830bd0940425b3bbf4fe068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
